[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "cancun"
allow_internal_expect_revert = true
via_ir = true

[profile.default.fuzz]
runs = 1_000

[profile.ci.fuzz]
runs = 5_000

[fmt]
ignore = ["lib/**", "out/**"]

[lint]
lint_on_build = false
ignore = ["lib/**", "out/**"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options