name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Continuous Integration
    uses: fomoweth/github-workflows/.github/workflows/foundry-ci.yml@main
    with:
      foundry-profile: ci
